grumphp:
    ascii:
        failed: ~
        succeeded: ~
    hooks_preset: vagrant
    git_hook_variables:
        VAGRANT_HOST_DIR: .
        VAGRANT_PROJECT_DIR: /vagrant
        EXEC_GRUMPHP_COMMAND: exec        
    tasks:
        composer:
            file: ./htdocs/composer.json
        phpcs:
            standard:
                - ./htdocs/vendor/drupal/coder/coder_sniffer/Drupal
                - ./htdocs/vendor/drupal/coder/coder_sniffer/DrupalPractice
            ignore_patterns:
                - cfg/
                - ./htdocs/web/libraries/
                - ./htdocs/web/lib/
                - ./htdocs/web/core/
                - ./htdocs/web/modules/contrib/
            triggered_by:
                - php
                - module
                - inc
                - install
                - test
                - profile
                - theme
                - twig
        git_commit_message:
            matchers:
                "Must contain JIRA ticket.": "/(Merge(.*)|(JIRACODE-([0-9]+): (.+)))/"
            case_insensitive: false
        yamllint: ~
        jsonlint:
            detect_key_conflicts: true
        xmllint: ~
        securitychecker_enlightn:
            lockfile: ./htdocs/composer.lock
            run_always: true
        phpstan:
            configuration: phpstan.neon
            triggered_by:
                - php
                - module
                - inc
                - install
                - test
                - profile
                - theme
                - twig
        git_blacklist:
            keywords:
                # PHP
                - " die("
                - " var_dump("
                - " print_r("
                - " print("
                - " dump("
                - " debug_backtrace("
                - " file_put_contents("
                - " exit;"
                - " echo "
                # JS
                - " console.log("
                # Drupal specific
                - " dpm("
                - " dsm("
                - " dpr("
                - " dpq("
                - " dprint_r("
                - " db_queryd("
                - " kpr("
                - " kprint_r("
                - " dd("
                - " ddebug_backtrace("
                - " drupal_debug("
                - " devel_render("
                - " kint("
            triggered_by:
                - php
                - module
                - inc
                - install
                - test
                - profile
                - theme
                - js
                - twig

